spring:
  application:
    name: first-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false