file:
  upload-dir: /code/upload
security:
  jwt:
    token:
      secret: ${JWT_SECRET:my-secret-key}
spring:
  application:
    name: first-project
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
spring-doc:
  pathsToMatch:
    - /auth/**
    - /api/**
  swagger-ui:
    use-root-path: true